baseURL                          = "https://mica-92.github.io/yogaenbaires/"   # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "es"                    # Default language for multilingual sites
# disqusshortname                 = ""                     # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                     # https://gohugo.io/templates/internal/#google-analytics
publishDir = "public"  # Ensure this is set



[params]
    themeStyle                   = "light"                  # Choose "light" or "dark" or "auto"
    favicon                      = "/yogaenbaires/img/fav.ico"          # Path to favicon file
    showMenu                     = true                    # Show navigation menu
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "01-2006"
    email                        = "desenrollatumat@gmail.com"   # E-mail address for contact section
    customCSS = ["css/custom.css"]
    basePath = "yogaenbaires"


    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/
    # plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)
    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = true                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = false                    # show all posts in an archive format
        numberOfProjectsToShow   = 6                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "America/Los_Angeles"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-US"                 # Language specific format to use

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        pinterest                = true

    # To enable giscus, the GitHub-discussions-based comment section,
    # input the repository for the discussions below. For more details, see
    # https://www.joelnitta.com/posts/2021-11-24_using-giscus/
    # and https://github.com/giscus/giscus
    [params.giscus]
        # repo = "github-user/github-repo" # Entering repo will enable giscus
        repo-id = "enter-repo-id"
        category = "Comments"
        category-id = "enter-category-id"
        mapping = "pathname"
        reactions-enabled = "1"
        emit-metadata = "0"
        theme = "light"
        lang = "en"

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://instagram.com/yogaenbaires"
        icon  = "instagram" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "https://www.tiktok.com/@yogaenbaires"  # For a direct email link, use "mailto:test@example.org".
        icon = "tiktok" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:mmicaninni92@email.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "envelope" # icon name without the 'fa-'
        icon_pack = "fas"



# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  estilo = "estilo"
  duracion = "duracion"
  intensidad = "intensidad"
  nivel = "nivele"
  otros = "otros"
  barrio = "barrio"
  descripcion = "descripcion"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "solarized-dark"
    tabWidth = 4

[languages.es]
    languageName     = "Español"
    languageCode     = "es"
    contentDir       = "content/en"
    weight           = 1
    title            = "Yoga en Baires"
    [languages.es.params]
        description  = "Yoga en Baires es un blog sobre reseñas de estudios de yoga en Buenos Aires, Argentina"
#        footerText   = "Si queres que tu sitio aparezca envianos un correo  <i class=\"fa fa-envelope\"></i><br><br>Hecho con <i class=\"fa fa-heart\"></i>   |   Buenos Aires, Argentina   |  <i class=\"fa-regular fa-copyright\"></i> YogaEnBaires, 2025"
